### ISSUE TITLE
Questions:

### ISSUE THREAD

**Issue by Uktltat** [Chocobo1/opus-tools_win32-build#12]
I don't get it, why isn't this a branch/fork out of the main opus page?
Btw does this work with the main libopus 1.5.2?

**Comment by Chocobo1** [comment]
>I don't get it, why isn't this a branch/fork out of the main opus page?

Because it requires more libraries than just opus.
You can see the dependencies (opus-tools, opus, flac, etc) on the very first landing page:
https://github.com/Chocobo1/opus-tools_win32-build?tab=readme-ov-file#opus-tools-unofficial-builds-

>Btw does this work with the main libopus 1.5.2?

At the release page: https://github.com/Chocobo1/opus-tools_win32-build/releases/tag/2024.12.03
It stated `v1.5.2` for `opus`, so that mean yes to your question.

**Comment by Uktltat** [comment]
Thx for the responses bro!
